### PR TITLE
Use the new API continuation mode

### PR DESCRIPTION
**Pull request by ricordisamoa**
https://lists.wikimedia.org/pipermail/wikitech-l/2015-June/081931.html

### CODE REVIEW

**Comment by ricordisamoa** [comment]
Keep in mind that, as continuation starts working again, the tool may hit MAX_API_CALLS rather frequently.
Maybe it could just warn instead of throwing an Exception.

**Comment by pietrodn** [comment]
Thanks for the patch. The script catches the exception for too many API calls and handles it correctly at line 221: it prints the partial list and warns the user that it may be incomplete.

**Comment by ricordisamoa** [comment]
Whoops, didn't see that. Thank you!

**Comment by ricordisamoa** [comment]
However it doesn't seem to show anything :(
https://tools.wmflabs.org/section-links/index.php?wikiDb=itwiki&wikiDirection=to&wikiPage=Roma

**Comment by pietrodn** [comment]
This doesn't necessarily indicate a bug. If the "to" option is selected, the tool must check the text of every reference, and it may run out of API calls before a reference with an incorrect link is found.

**Comment by pietrodn** [comment]
This, for example, works:
https://tools.wmflabs.org/section-links/index.php?wikiDb=itwiki&wikiDirection=to&wikiPage=Professionista

**Comment by ricordisamoa** [comment]
Oh, my fault.

**Pull request merged**
